server:
  port: 30155
  servlet:
    context-path: /flink-acorn

logging:
  group:
    acorn: com.isxcode.acorn
  level:
    acorn: debug

acorn:
  plugin:
    key: acorn-key
    flink-port: 8081
    storage-tmp: false
    tmp-dir: /opt/flink-acorn/tmp
