spring:
  profiles:
    active: acorn
  banner:
    location: classpath:banner.txt

application:
  version: 1.2.0

server:
  port: 30155
  servlet:
    context-path: /flink-acorn

acorn:
  check-env: true
  secret: acorn-key
