server:
  servlet:
    context-path: /flink-acorn

spring:
  profiles:
    active: acorn

acorn:
  plugin:
    server-key: dehoop-key
    flink-host: 127.0.0.1
    flink-port: 30114
    storage-tmp: false
    hive-conf-path: /opt/flink/conf
    log-dir: /opt/acorn/tmp/log
    tmp-dir: /opt/acorn/tmp
