acorn:
  client:
    server:
      default:
        host: 121.89.213.24
        port: 30155
        key: acorn-key
      node2:
        host: 5.142.131.65
        port: 30155
        key: acorn-key
      inner:
        host: 192.168.66.66
        port: 30155
        key: acorn-key
